# Generated by Django 5.2.15 on 2026-06-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmtoken',
            name='token',
             field=models.CharField(help_text="Token FCM unique de l'appareil", max_length=255, unique=True),
        ),
    ]
