# Generated by Django 5.2.15 on 2026-06-26 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_create_legacy_video_tables_sql'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertSpace',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('organization_id', models.BigIntegerField()),
                ('telegram_chat_id', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=2)),
                ('token_web_connector', models.CharField(blank=True, max_length=255, null=True)),
                ('url_web_connector', models.CharField(blank=True, max_length=255, null=True)),
                ('send_telegram_message', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Espace de surveillance',
                'verbose_name_plural': 'Espaces de surveillance',
                'db_table': 'notifications_space',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VideoTheftAlert',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100)),
                ('recording_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé - Vol confirmé'), ('REJECTED', 'Rejeté - Fausse alerte')], default='PENDING', max_length=30)),
                ('send_date', models.DateField(blank=True, null=True)),
                ('create_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
                ('camera_id', models.BigIntegerField()),
                ('modified_by_id', models.CharField(blank=True, max_length=32, null=True)),
                ('send_notified', models.BooleanField(default=False)),
                ('sub_status', models.CharField(blank=True, default='', max_length=30)),
                ('original_path', models.CharField(blank=True, max_length=255, null=True)),
                ('probability', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('detected_by_model', models.BooleanField(blank=True, null=True)),
                ('nb_alerts', models.IntegerField(blank=True, null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=254, null=True)),
                ('approval_result', models.CharField(blank=True, max_length=2, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('modified_by_qualification_id', models.CharField(blank=True, max_length=32, null=True)),
                ('qualification', models.CharField(blank=True, choices=[('vol', 'Vol confirmé'), ('suspicious', 'Comportement suspect'), ('false_alarm', 'Fausse alerte')], max_length=50, null=True)),
                ('qualification_update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Alerte vidéo',
                'verbose_name_plural': 'Alertes vidéo',
                'db_table': 'notifications_video',
                'ordering': ['-recording_date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PredictionNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_uuid', models.CharField(db_index=True, help_text='UUID unique de la notification N8N', max_length=100, unique=True)),
                ('type', models.CharField(choices=[('prediction', "Prédiction d'affluence"), ('report', 'Rapport analytique'), ('alert', 'Alerte système'), ('custom', 'Notification personnalisée')], default='prediction', help_text='Type de notification', max_length=50)),
                ('title', models.CharField(help_text='Titre de la notification', max_length=255)),
                ('message', models.TextField(help_text='Corps du message/texte principal')),
                ('date', models.DateField(help_text='Date concernée par la prédiction')),
                ('visiteurs_prevus', models.IntegerField(default=0, help_text='Nombre de visiteurs prévus')),
                ('profil_dominant', models.CharField(blank=True, default='', help_text="Profil dominant de visiteurs (ex: 'Femmes 25-35')", max_length=255)),
                ('niveau_affluence', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('very_high', 'Très élevé')], default='medium', help_text="Niveau d'affluence prévu", max_length=50)),
                ('heure_pointe', models.CharField(blank=True, default='', help_text="Heure de pointe estimée (ex: '14h30')", max_length=50)),
                ('model', models.CharField(default='llama3.2:3b-instruct-q4_K_M', help_text='Modèle LLM utilisé pour générer la prédiction', max_length=255)),
                ('confidence_score', models.FloatField(blank=True, help_text='Score de confiance de la prédiction (0-1)', null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='Marqué comme lue')),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp de création de la notification')),
                ('sent_at', models.DateTimeField(blank=True, help_text="Timestamp d'envoi push (si envoyé)", null=True)),
                ('read_at', models.DateTimeField(blank=True, help_text='Timestamp de première lecture', null=True)),
                ('tags', models.CharField(blank=True, help_text="Tags séparés par virgule (ex: 'urgent,affluence')", max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Données JSON supplémentaires')),
            ],
            options={
                'verbose_name': 'Notification de prédiction',
                'verbose_name_plural': 'Notifications de prédictions',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='PushNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict, help_text='Données custom pour la notification')),
                ('status', models.CharField(choices=[('queued', "En file d'attente"), ('sent', 'Envoyée'), ('failed', 'Échouée'), ('bounced', 'Rejetée')], default='queued', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_count', models.IntegerField(default=0, help_text="Nombre d'appareils ayant reçu l'alerte")),
                ('error_count', models.IntegerField(default=0, help_text="Nombre d'erreurs lors de l'envoi")),
                ('errors', models.JSONField(blank=True, default=list, help_text="Liste des erreurs d'envoi")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Journal d'envoi FCM",
                'verbose_name_plural': "Journaux d'envoi FCM",
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='NotificationsSpace',
        ),
        migrations.DeleteModel(
            name='NotificationsVideo',
        ),
        migrations.AlterModelOptions(
            name='fcmtoken',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Token FCM', 'verbose_name_plural': 'Tokens FCM'},
        ),
        migrations.AddField(
            model_name='fcmtoken',
            name='device_info',
            field=models.CharField(blank=True, help_text="Infos sur l'appareil (OS, version)", max_length=255),
        ),
        migrations.AddField(
            model_name='fcmtoken',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Token actif ou révoqué'),
        ),
        migrations.AlterField(
            model_name='fcmtoken',
            name='token',
            field=models.CharField(help_text="Token FCM unique de l'appareil", max_length=500, unique=True),
        ),
        migrations.AddIndex(
            model_name='predictionnotification',
            index=models.Index(fields=['date', '-generated_at'], name='history_pre_date_3cb4fd_idx'),
        ),
        migrations.AddIndex(
            model_name='predictionnotification',
            index=models.Index(fields=['is_read', '-generated_at'], name='history_pre_is_read_bf9e6c_idx'),
        ),
        migrations.AddIndex(
            model_name='predictionnotification',
            index=models.Index(fields=['type'], name='history_pre_type_b4baf5_idx'),
        ),
        migrations.AddField(
            model_name='pushnotificationlog',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_logs', to='history.predictionnotification'),
        ),
    ]
